"""empty message

Revision ID: 0d548bdda88e
Revises: 2f9223c4063e
Create Date: 2025-04-18 12:35:41.984193

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0d548bdda88e'
down_revision = '2f9223c4063e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('envio', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('envio', sa.Column('ciudad', sa.String(length=100), nullable=False))
    op.add_column('envio', sa.Column('codigo_postal', sa.String(length=20), nullable=False))
    op.add_column('envio', sa.Column('pais', sa.String(length=100), nullable=False))
    op.add_column('envio', sa.Column('estado_envio', sa.String(length=100), nullable=True))
    op.add_column('envio', sa.Column('fecha_creacion', sa.DateTime(), nullable=True))
    op.drop_constraint('envio_ibfk_1', 'envio', type_='foreignkey')
    op.drop_column('envio', 'id_orden')
    op.drop_column('envio', 'id_envio')
    op.drop_column('envio', 'fecha')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('envio', sa.Column('fecha', mysql.DATETIME(), nullable=True))
    op.add_column('envio', sa.Column('id_envio', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.add_column('envio', sa.Column('id_orden', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('envio_ibfk_1', 'envio', 'orden', ['id_orden'], ['id_orden'])
    op.drop_column('envio', 'fecha_creacion')
    op.drop_column('envio', 'estado_envio')
    op.drop_column('envio', 'pais')
    op.drop_column('envio', 'codigo_postal')
    op.drop_column('envio', 'ciudad')
    op.drop_column('envio', 'id')
    # ### end Alembic commands ###
