"""empty message

Revision ID: 7354742bbe2f
Revises: 2a03a0214ded
Create Date: 2025-04-16 22:29:44.352643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7354742bbe2f'
down_revision = '2a03a0214ded'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paypal_detalle',
    sa.Column('id_paypal', sa.Integer(), nullable=False),
    sa.Column('id_pago', sa.Integer(), nullable=True),
    sa.Column('email_paypal', sa.String(length=150), nullable=False),
    sa.Column('confirmacion_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_pago'], ['pago.id_pago'], ),
    sa.PrimaryKeyConstraint('id_paypal')
    )
    op.create_table('transferencia_detalle',
    sa.Column('id_transferencia', sa.Integer(), nullable=False),
    sa.Column('id_pago', sa.Integer(), nullable=True),
    sa.Column('nombre_titular', sa.String(length=100), nullable=False),
    sa.Column('banco_origen', sa.String(length=100), nullable=False),
    sa.Column('numero_cuenta', sa.String(length=100), nullable=False),
    sa.Column('comprobante_url', sa.String(length=255), nullable=True),
    sa.Column('fecha_transferencia', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_pago'], ['pago.id_pago'], ),
    sa.PrimaryKeyConstraint('id_transferencia')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transferencia_detalle')
    op.drop_table('paypal_detalle')
    # ### end Alembic commands ###
